{{- if .Values.placementConfig.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "couchdb.fullname" . }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: post-install-job
        image: {{ .Values.placementConfig.image.repository }}:{{ .Values.placementConfig.image.tag }}
        imagePullPolicy: {{ .Values.placementConfig.image.pullPolicy }}
        args: ["--script", "1"]
        envFrom:
          - secretRef:
              name: couchdb-couchdb
{{- end -}}