# Add doc
{{- if .Values.volumeMonitorJob.enabled }} 
apiVersion: batch/v1
kind: CronJob
metadata:
  name: monitor-volumes-size
spec:
  schedule: {{ .Values.volumeMonitorJob.schedule }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      completions: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: couchdb-volume-monitor
            image: {{ .Values.volumeMonitorJob.image.repository }}:{{ .Values.volumeMonitorJob.image.tag }}
            args: ["--volume-monitor"]
            imagePullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: couchdb-couchdb
            - configMapRef:
                name: {{ template "couchdb.fullname" . }}
            env:
              - name: NAMESPACE
                value: {{ .Release.Namespace }}
              - name: VOLUME_THRESHOLD
                value: {{ .Values.volumeMonitorJob.volumeConfigParams.volumeThreshold | quote }}
              - name: VOLUME_RESIZE_PERCENTAGE
                value: {{ .Values.volumeMonitorJob.volumeConfigParams.volumeResizePercentage | quote }}
              - name: VOLUME_MOUNT_PATH
                value: {{ .Values.volumeMonitorJob.volumeConfigParams.volumeMountPath }}
{{- end }}
